### ISSUE TITLE
Error in the manual buy example

### ISSUE THREAD

**Issue by fasogbon** [chainstacklabs/pump-fun-bot#14]
Please, I am having the following error. Do I need to get a better RPC?
I am currently using chainlink one and i am still having this error

`New token created:
{
  "name": "Bill",
  "symbol": "Bill",
  "uri": "https://ipfs.io/ipfs/Qmcj69Qnqq13fJp3ggfraB3bTCNgg3oy16aqsTa8LsQuP7",
  "mint": "AR1hiozJuJSE5bJ51scMeqVSEJa5GunRoSrbgpnRpump",
  "bondingCurve": "AATFWxsGx7zLyW2awd1iQ9PuBA8wqppqHaiveP5BYsu3",
  "associatedBondingCurve": "F2r4B88tw7trf53SKXhyRWnmea7bTuEjR9bzJzzNBcXW",
  "user": "EB11GPWhrJubQ2y21ZfUb2th1SnsVJ3EDwNd7rVGTRkd"
}
Waiting for 15 seconds for things to stabilize...
Bonding curve address: AATFWxsGx7zLyW2awd1iQ9PuBA8wqppqHaiveP5BYsu3
Token price: 0.0000004109 SOL
Buying 0.000010 SOL worth of the new token with 30.0% slippage tolerance...

Traceback (most recent call last):
  File "C:\Users\AppData\Roaming\Python\Python312\site-packages\solana\exceptions.py", line 58, in argument_decorator
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Roaming\Python\Python312\site-packages\solana\rpc\providers\async_http.py", line 59, in make_request
    raw = await self.make_request_unparsed(body)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Roaming\Python\Python312\site-packages\solana\rpc\providers\async_http.py", line 66, in make_request_unparsed
    return _after_request_unparsed(raw_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Roaming\Python\Python312\site-packages\solana\rpc\providers\core.py", line 136, in _after_request_unparsed
    raw_response.raise_for_status()
  File "C:\Users\AppData\Roaming\Python\Python312\site-packages\httpx\_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '429 Too Many Requests' for url 'https://solana-mainnet.core.chainstack.com/db6742819b8c3eefd5b614c6a44343ab'
For more information check: https://httpstatuses.com/429

The above exception was the direct cause of the following exception:`

**Comment by akegaviar** [comment]
Hey there, looks like you are hitting the requests per second (RPS) limit. Are you on the free developer plan? You may want to upgrade to the Growth plan for a higher RPS limit or reduce the number of calls you are making per second.

For the current limits, see our Developer Portal: [Limits](https://docs.chainstack.com/docs/limits)

**Comment by akegaviar** [comment]
Hey there, starting from the next week (**week of March 10**) we'll be rolling out updates to the bot v2 based on the feedback and the reported issues, including updating to the latest libs, better error handling etc. We are already actively working on it.

That'll be in a separate branch.

So for this particular issue, I suggest trying out a new version in a separate branch. We'll let you know.

Also, check out the readme for the roadmap that I just added in the README file for the full overview.

**Comment by smypmsa** [comment]
⚠ The completely refactored bot has been merged into the main branch. Please use the updated bot.
